### ISSUE TITLE
Code Formatter

### ISSUE THREAD

**Issue by Arun152k** [rohitgeddam/FindMyRoomie#111]
Please create a config file for code formatter. You might try using black

**Comment by Arun152k** [comment]
@rohitgeddam, I suppose you added pyproject.toml for the black configuration. If done, consider closing the issue.

**Comment by rohitgeddam** [comment]
Yes I have added configuration for Black formatter in pyproject.toml. We need to run Black in command line each time befor e we push to fix all flake8 linting errors.
