### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by Arun152k** [rohitgeddam/FindMyRoomie#119]
Check if we need to add any of these shields mentioned in the SE project GitHub page. 

![image](https://user-images.githubusercontent.com/52373569/194487856-21fec25a-5611-4c60-a950-f9f0dff39bdd.png)

**Comment by kironjayesh** [comment]
I have added most badges required for the project (excluding rating, donations per week, etc,)

**Comment by Darkviper7** [comment]
All  badges added
