### ISSUE TITLE
Fix LiveServer test

### ISSUE THREAD

**Issue by Arun152k** [rohitgeddam/FindMyRoomie#126]
Don't fix it in Main. Create a new branch and work on it.

**Comment by shandlermason** [comment]
It works. It was a formatting issue. Please stop commenting out my code.

**Comment by Arun152k** [comment]
I don't see it working, look at the action report. Push into the main branch only if it works in your local system. Even then, push it into a new branch and check if it passes the GitHub actions. We can merge it into the main later.

**Comment by Arun152k** [comment]
All of us were unable to fix this. Deleting the test. We have already added more tests.
