### ISSUE TITLE
create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by shandlermason** [rohitgeddam/FindMyRoomie#60]
The files CONTRIBUTING.md lists coding standards and lots of tips on how to extend the system without screwing things up

**Comment by Arun152k** [comment]
Created it. But it has to be updated properly.

**Comment by kironjayesh** [comment]
I will work on it

**Comment by Arun152k** [comment]
Kiron, close the issue if it is done.

**Comment by kironjayesh** [comment]
Done!
