### ISSUE TITLE
CITATION.cff

### ISSUE THREAD

**Issue by Arun152k** [rohitgeddam/FindMyRoomie#79]
Guys, check the CITATION.cff in the 'develop' branch. Check your names and add your orcid ID.
If you don't have an Orcid ID, please create one here:
https://orcid.org/

**Comment by Darkviper7** [comment]
I updated my citation

**Comment by Arun152k** [comment]
@shandlermason, please update this with your orcid ID.

**Comment by shandlermason** [comment]
Ok will do in morning
